# Generated by Django 3.0.2 on 2020-04-16 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200416_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Science'), ('2', 'Tech'), ('3', 'Polity'), ('4', 'Miscellaneous')], default='4', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(choices=[('1', 'Science'), ('2', 'Tech'), ('3', 'Polity'), ('4', 'Miscellaneous')], default='4', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='articles.Category'),
        ),
    ]
