# Generated by Django 3.0.2 on 2020-04-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200417_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.IntegerField(choices=[('1', 'Science'), ('2', 'Tech'), ('3', 'Polity'), ('4', 'Miscellaneous')], default='4'),
        ),
    ]
