# Generated by Django 3.0.2 on 2020-04-16 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200417_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(choices=[('SC', 'Science'), ('TE', 'Tech'), ('PO', 'Polity'), ('MI', 'Miscellaneous')], default='MI', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='articles.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('SC', 'Science'), ('TE', 'Tech'), ('PO', 'Polity'), ('MI', 'Miscellaneous')], default='MI', max_length=20),
        ),
    ]
