# Generated by Django 3.0.2 on 2020-04-16 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20200417_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='MI', on_delete=django.db.models.deletion.CASCADE, to='articles.Category'),
        ),
    ]
