# Generated by Django 3.0.2 on 2020-04-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20200417_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('SC', 'Science'), ('TE', 'Tech'), ('PO', 'Polity'), ('MI', 'Miscellaneous')], default='MI', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
