# Generated by Django 3.0.2 on 2020-04-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20200417_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Science', 'Science'), ('Tech', 'Tech'), ('Polity', 'Polity'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=20),
        ),
    ]
