# Generated by Django 3.0.2 on 2020-04-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20200417_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='categorize',
        ),
    ]
